### ISSUE TITLE
FYI this seems to have broken the [Tekton Downstream e2e Test](https://github.com/knative/pkg/actions/workflows/tekton-downstream.yaml)

### ISSUE THREAD

**Issue by dprotaso** [knative/actions#86]
FYI this seems to have broken the [Tekton Downstream e2e Test](https://github.com/knative/pkg/actions/workflows/tekton-downstream.yaml)

https://github.com/knative/pkg/actions/runs/3317533673/jobs/5480506677#step:7:542

The test is now running with allllll the tags specified, which seems to result in baffling stdlib import cycle errors -- things just weren't meant to be built with all these tags:

```
Building with tags: 386,aix,amd64,appengine,arm,arm64,blahblh,cgo,clientlogmode,codegen,compile,complex_tests,conformance,darwin,dragonfly,e2e,ec2env,examples,exclude_disk_quota,freebsd,gc,gccgo,generate,go1.1,go1.10,go1.11,go1.12,go1.13,go1.14,go1.15,go1.16,go1.17,go1.18,go1.19,go1.2,go1.4,go1.5,go1.6,go1.7,go1.8,go1.9,gofuzz,grpcgoid,ignore,illumos,include_gcs,include_oss,integration,journald,journald_compat,js,jsoniter,jsoniter_sloppy,libdm_dlsym_deferred_remove,libdm_no_deferred_remove,linux,mips,mips64,mips64le,mipsle,modhack,nacl,netbsd,never,no_lcow,no_rdt,noasm,none,noresumabledigest,openbsd,plan9,purego,race,seccomp,solaris,spiffeid_charset_backcompat,static_build,tools,windows,windows_e2e,zos
```

The last successful run of the Tekton e2e test is here: https://github.com/knative/pkg/actions/runs/3198272700/jobs/5222584998#step:7:568

and says:

```
Building with tags: conformance e2e examples 
```

cc @vdemeester @dprotaso

_Originally posted by @imjasonh in https://github.com/knative/actions/issues/72#issuecomment-1290826874_

**Comment by dprotaso** [comment]
I think it would make sense to read the tags from the `.golangci.yaml` file and let maintainers update that vs. trying to infer tags ourselves

**Comment by vdemeester** [comment]
cc @imjasonh as I think we saw this earlier somewhere

**Comment by cardil** [comment]
Running on tektoncd/pipeline looks different:

```
$ go run knative.dev/test-infra/tools/go-ls-tags@latest --joiner=,
conformance,e2e,examples,linux,tools,windows,windows_e2e
```

**Comment by cardil** [comment]
Okay. I got the culprit. The `update-codegen` script is creating a gopath withing the downstream repo at `./.gopath`. The `go-ls-tags` scans that folder, which contains the whole gopath.

That directory should be removed before testing the compilation. Or better, to create it on `/tmp` dir, not inside the project.

**Comment by vdemeester** [comment]
@cardil ah interesting.. I wouldn't have thought this would be the culprit 😅

**Comment by imjasonh** [comment]
FWIW I agree with @dprotaso and think this will result in fewer surprises long-term:

> I think it would make sense to read the tags from the `.golangci.yaml` file and let maintainers update that vs. trying to infer tags ourselves

Deleting `.gopath` might unblock Tekton for now, but won't stop us from hitting other landmines later.

**Comment by cardil** [comment]
I plan to add some features to go-ls-tags tool:

- reading tags from `.golangci.yml` file
- per repo configurability
- skipping `.` prefixed dirs
- skipping other platform tags (like windows)

**Comment by cardil** [comment]
There's a PR for `.gopath` removal: #87

**Comment by dprotaso** [comment]
@cardil pointed out the .gopath removal is specific to tekton. 

Rather than adding a workaround in the action @imjasonh @vdemeester can you update the tekton scripts?

It seems like it should be doing it here - https://github.com/tektoncd/pipeline/blob/d31035559d0a044f7c29fe00adc1aa956f55b530/hack/setup-temporary-gopath.sh#L60 but you're not unsetting the env var?

/unassign @cardil 
/assign @vdemeester @imjasonh

**Comment by cardil** [comment]
Also, the `go-ls-tags` tool already supports a `.gotagsignore`. You could specify tags to ignore in that file.

I think it makes sense to create such file in `tektoncd/pipeline` root dir with contents:

```
tools
windows
```

BTW. This in-flight PR should fix that feature :-P https://github.com/knative/test-infra/issues/3603

**Comment by vdemeester** [comment]
@dprotaso @cardil any reason for not ignoring *hidden* folders (aka `.gopath`, …) in `go-ls-tags` ?

The environment variable is not "set" for the user (aka running `./hack/update-codegen.sh` doesn't set `GOPATH` on my "shell"). *But* we keep the `.gopath` around indeed, which seems to be picked up by the `go-ls-tags` tool. 

The main *issue* with that script (and `go`) is that.. as a user, I can't delete `.gopath` without having to do a `sudo`, and we cannot really automatically do that and ask the user for there password just to update the generated code.

**Comment by cardil** [comment]
Re @vdemeester:

> +dprotaso +cardil any reason for not ignoring _hidden_ folders (aka `.gopath`, …) in `go-ls-tags` ?

See: https://github.com/knative/actions/issues/86#issuecomment-1303890880

> The environment variable is not "set" for the user (aka running `./hack/update-codegen.sh` doesn't set `GOPATH` on my "shell"). _But_ we keep the `.gopath` around indeed, which seems to be picked up by the `go-ls-tags` tool.
> 
> The main _issue_ with that script (and `go`) is that.. as a user, I can't delete `.gopath` without having to do a `sudo`, and we cannot really automatically do that and ask the user for there password just to update the generated code.

Why are you needing the sudo? That's super strange, and ugly. If files are created normally, why root access is required? The files shouldn't be created as root.

**Comment by vdemeester** [comment]
@cardil yeah I saw your comment after sending mine 😅 

> Why are you needing the sudo? That's super strange, and ugly. If files are created normally, why root access is required? The files shouldn't be created as root.

That I don't know, but that's definitely what is happening…

```
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/pod/state.go': Permission denied                                                                                      
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/pod/reconciler.go': Permission denied                                                                                 
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/namespace/controller.go': Permission denied                                                                           
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/namespace/state.go': Permission denied                                                                                
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/namespace/reconciler.go': Permission denied                                                                           
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/node/controller.go': Permission denied                                                                                
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/node/state.go': Permission denied                                                                                     
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/node/reconciler.go': Permission denied                                                                                
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/configmap/controller.go': Permission denied                                                                           
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/configmap/state.go': Permission denied                                                                                
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/core/v1/configmap/reconciler.go': Permission denied                                                                           
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta1/deployment/controller.go': Permission denied                                                                     
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta1/deployment/state.go': Permission denied                                                                          
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go': Permission denied                                                                     
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1/deployment/controller.go': Permission denied                                                                          
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1/deployment/state.go': Permission denied                                                                               
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1/deployment/reconciler.go': Permission denied                                                                          
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta2/deployment/controller.go': Permission denied                                                                     
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta2/deployment/state.go': Permission denied                                                                          
rm: cannot remove '.gopath/pkg/mod/knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go': Permission denied        
```

**Comment by dprotaso** [comment]
cc @cardil tekton downstream removed the `.gopath` in the repo dir but I still see it failing 

https://github.com/knative/pkg/actions/runs/3525878711/jobs/5913134519#step:7:533

What's odd is that serving has a `tools` tag as well but it doesn't fail?

**Comment by cardil** [comment]
I wrote here https://github.com/knative/actions/issues/86#issuecomment-1303888212 that they should create a `.gotagsignore` with contents to make build pass.

```
tools
windows
```

**Comment by cardil** [comment]
Here's a PR to fix this https://github.com/tektoncd/pipeline/pull/5783

**Comment by dprotaso** [comment]
What's odd is serving has a `tools` tag but it doesn't error out

It might be simpler to give control to repos to opt into which tags they compile by reading this file and looking at the `run.build-tags`

https://github.com/knative/serving/blob/638e11418b2bb98d16c517d81cf39d13a859405a/.golangci.yaml#L4-L6

**Comment by imjasonh** [comment]
Here's Tekton's:

- https://github.com/tektoncd/pipeline/blob/main/.golangci.yml#L46
- https://github.com/tektoncd/triggers/blob/main/.golangci.yml#L3
- https://github.com/tektoncd/chains/blob/main/.golang-ci.yaml#L24

(all `e2e`)

This would solve the build tags issues, but not the `go build ./...` issue. That could be solved by only testing `./test/...` where all our e2e tests are.

**Comment by cardil** [comment]
@dprotaso I already said I'll add reading the `.golangci.yml`, as an option.

I don't think it should be the default setting. Here' you have a proof: Tekton pipelines have the following tags: `conformance,e2e,examples,linux,tools,windows,windows_e2e`. Without platform ones that: `conformance,e2e,examples,tools`.

The `.golangci.yml` lists only `e2e` tag.  The proper build test should test the build versus `conformance,e2e,examples,tools` (maybe without tools).

**Comment by dprotaso** [comment]
>  The proper build test should test the build versus 

I'd say the repo should have influence over the test  - ie. `tools` should be excluded. Tekton should probably add conformance

Oddly - serving has a `tools` tag but it's not excluded for some reason and `go-ls-tags` doesn't show it
